title: "Camille Pouchol"
description: "Personal academic website"
url: "https://camillepouchol.github.io"
markdown: kramdown
theme: minima

header_pages:
  - publications.md
  - teaching.md
  - cv.md
  - contact.md
