project:
  type: website
  output-dir: docs

website:
  site-url: "https://cpouchol.github.io/"
  title: "Camille Pouchol"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.md
        text: Publications
      - href: enseignement.md
        text: Enseignement
      - href: contact.md
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

lang: en
