---
layout: default
title: Publications
---

## Preprints

- [Generalisation of Farkas' lemma beyond closedness: a constructive approach via Fenchel-Rockafellar duality](https://arxiv.org/pdf/2603.11859v1)   
   with E. Trélat, C. Zhang

- [Computer-assisted proofs of non-reachability for linear parabolic PDEs under bounded control constraints](https://hal.science/hal-05357694/file/HPPZ_computer_assisted_PDE.pdf)  
   with I. Hasenohr, Y. Privat, C. Zhang 

- [Estimating the intensity of a filtered Poisson point process on $\mathbb{R}^d$](https://hal.science/hal-05084273/file/Article_Principal.pdf)  
   with R. Abergel, F. Comte, C. Duval

- [Random Leja points](https://arxiv.org/pdf/2406.11499v1)  

- [Constructive reachability for linear control problems under conic constraints](https://arxiv.org/pdf/2405.07684v1)  
   with E. Trélat, C. Zhang  

## Journal articles

<ol class="publication-list" reversed start="21">
  <li>
    <a href="./assets/publications/HP2024.pdf">Regularisation for the approximation of functions by mollified discretisation methods</a><br>
    with M. Hoffmann<br>
    <em>SIAM Journal on Uncertainty Quantification</em> (2025)
  </li>
  <li>
    <a href="./assets/publications/HPPZ2024.pdf">Computer-assisted proofs of non-reachability for linear finite-dimensional control systems</a><br>
    with I. Hasenohr, Y. Privat, C. Zhang<br>
    <em>SIAM Journal on Control and Optimization</em> (2025)
  </li>
  <li>
    <a href="./assets/publications/GJJP2023.pdf">An integrative phenotype-structured partial differential equation model for the population dynamics of epithelial-mesenchymal transition</a><br>
    with J. Guilberteau, P. Jain, M. K. Jolly, N. Pouradier Duteil<br>
    <em>NPJ Systems Biology and Applications</em> (2025)
  </li>
  <li>
    <a href="./assets/publications/DP2024.pdf">Solving Abel integral equations by regularisation in Hilbert scales</a><br>
    with C. Della Valle<br>
    <em>Journal of Mathematical Analysis and Applications</em> (2024)
  </li>
  <li>
    <a href="./assets/publications/PTZ2024.pdf">Approximate control of parabolic equations with on-off shape controls by Fenchel duality</a><br>
    with E. Trélat, C. Zhang<br>
    <em>Annales de l'Institut Poincaré C - Analyse non linéaire</em> (2024)
  </li>
  <li>
    <a href="./assets/publications/GPP2024.pdf">Long-time behaviour of an advection-selection equation</a><br>
    with J. Guilberteau, N. Pouradier Duteil<br>
    <em>Discrete and Continuous Dynamical Systems - B</em> (2024)
  </li>
  <li>
    <a href="./assets/publications/PV2024.pdf">Linear inverse problems with nonnegativity constraints: singularity of optimisers</a><br>
    with O. Verdier<br>
    <em>Inverse Problems and Imaging</em> (2024)
  </li>
  <li>
    <a href="./assets/publications/CKP2023.pdf">A phenotype-structured model for the tumour-immune response</a><br>
    with Z. Kaid, J. Clairambault<br>
    <em>Mathematical Modelling of Natural Phenomena</em> (2023)
  </li>
  <li>
    <a href="./assets/publications/EFOPPV2022.pdf">Pandemic Lock-down, Isolation, and Exit Policies Based on Machine Learning Predictions</a><br>
    with T. Evgeniou, M. Fekom, A. Ovchinnikov, R. Porcher, N. Vayatis<br>
    <em>Production and Operations Management</em> (2022)
  </li>
  <li>
    <a href="./assets/publications/GPP2021.pdf">Monostability and bistability of biological switches</a><br>
    with J. Guilberteau, N. Pouradier Duteil<br>
    <em>Journal of Mathematical Biology</em> (2021)
  </li>
  <li>
    <a href="./assets/publications/PV2021.pdf">Statistical model and ML-EM algorithm for emission tomography with known movement</a><br>
    with O. Verdier<br>
    <em>Journal of Mathematical Imaging and Vision</em> (2021)
  </li>
  <li>
    <a href="./assets/publications/BEFOPV2020.pdf">SEAIR framework accounting for a personalised risk prediction score: application to the Covid-19 epidemic</a><br>
    with O. Boulant, M. Fekom, T. Evgeniou, A. Ovchinnikov, R. Porcher, N. Vayatis<br>
    <em>Image Processing On Line</em> (2020)
  </li>
  <li>
    <a href="./assets/publications/LP2020.pdf">Asymptotic analysis of selection-mutation models in the presence of multiple fitness peaks</a><br>
    with T. Lorenzi<br>
    <em>Nonlinearity</em> (2020)
  </li>
  <li>
    <a href="./assets/publications/PV2020.pdf">The ML-EM algorithm in continuum: sparse measure solutions</a><br>
    with O. Verdier<br>
    <em>Inverse Problems</em> (2020)
  </li>
  <li>
    <a href="./assets/publications/BPPS2019.pdf">Hele-Shaw limit for a system of two reaction-(cross-)diffusion equations for living tissues</a><br>
    with F. Bubba, B. Perthame, M. Schmidtchen<br>
    <em>Archive for Rational Mechanics and Analysis</em> (2019)
  </li>
  <li>
    <a href="./assets/publications/BFVAPS2019.pdf">A chemotaxis-based explanation of spheroid formation in 3D cultures of breast cancer cells</a><br>
    with F. Bubba, N. Ferrand, G. Vidal, L. Almeida, B. Perthame, M. Sabbah<br>
    <em>Journal of Theoretical Biology</em> (2019)
  </li>
  <li>
    <a href="./assets/publications/PTZ2019.pdf">Phase portrait control of 1D monostable and bistable reaction-diffusion equations</a><br>
    with E. Trélat, E. Zuazua<br>
    <em>Nonlinearity</em> (2019)
  </li>
  <li>
    <a href="./assets/publications/OP2019.pdf">Combination of direct methods and homotopy in numerical optimal control: application to the optimization of chemotherapy in cancer</a><br>
    with A. Olivier<br>
    <em>Journal of Optimization Theory and Applications</em> (2019)
  </li>
  <li>
    <a href="./assets/publications/ABPP2019.pdf">Energy and implicit discretization of the Fokker-Planck and Keller-Segel type equations</a><br>
    with L. Almeida, F. Bubba, B. Perthame<br>
    <em>Networks and Heterogeneous Media</em> (2019)
  </li>
  <li>
    <a href="./assets/publications/PT2018.pdf">Global stability with selection in integro-differential Lotka-Volterra systems modelling trait-structured populations</a><br>
    with E. Trélat<br>
    <em>Journal of Biological Dynamics</em> (2018)
  </li>
  <li>
    <a href="./assets/publications/CLPT2018.pdf">Asymptotic analysis and optimal control of an integro-differential system modelling healthy and cancer cells exposed to chemotherapy</a><br>
    with J. Clairambault, A. Lorz, E. Trélat<br>
    <em>Journal de Mathématiques Pures et Appliquées</em> (2018)
  </li>
</ol>

## Proceedings

<ol class="publication-list" reversed start="2">
  <li>
    <a href="./assets/publications/OPV2019.pdf">Spatiotemporal PET reconstruction using ML-EM with learned diffeomorphic deformation</a><br>
    with O. Öktem, O. Verdier<br>
    MLMIR (2019)
  </li>
  <li>
    <a href="./assets/publications/CP2019.pdf">A survey of adaptive cell population dynamics models of emergence of drug resistance in cancer, and open questions about evolution and cancer</a><br>
    with J. Clairambault<br>
    Biomath (2019)
  </li>
</ol>

## Notes

- [On the stability of the state 1 in the non-local Fisher-KPP equation in bounded domains](./assets/publications/P2018.pdf)  
  *Comptes Rendus Mathematique* (2018)

## Book chapters

- [Why is evolution important in cancer and what mathematics should be used to treat cancer? Focus on drug resistance](./assets/publications/ACCLLPT2018.pdf)  
  with L. Almeida, R. Chisholm, J. Clairambault, T. Lorenzi, A. Lorz, E. Trélat  
  Biomat (2018)

## PhD thesis

- [Analysis, control and optimisation of PDEs, application to the biology and therapy of cancer](https://hal.science/tel-01889253v2/document)  
  PhD thesis 

## Popularisation (in French)

- [Combattre les tumeurs résistantes à la chimiothérapie grâce au contrôle optimal](https://images.math.cnrs.fr/freeze/Combattre-les-tumeurs-resistantes-a-la-chimiotherapie-grace-au-controle-optimal.html)  
  with E. Trélat  
  Images des mathématiques
